# Day 18 of 100 days of Data Science

a crowdsourced Data Science learning program by Mr. Sharan

---

## Numpy: Intro and Array Creation

__Numpy stands for Numerical Python, it is faster than list and is a replacement of Matlab. Used for linear algebra, matrix operations and fourier transformation.__

In [1]:
import numpy as np

### Arrays

__Syntax:__ *numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)*

__One Dimentional Array__

In [2]:
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

__Setting the Minimum Dimension as 2__

In [3]:
arr1 = np.array([1, 2, 3], ndmin=2)
print(arr1.ndim)
arr1

2


array([[1, 2, 3]])

__Two Dimentional Array__

In [4]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)
print("Array Shape: ", arr2.shape)
print("Dimensions: ", arr2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array Shape:  (2, 5)
Dimensions:  2


In [5]:
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr2d)
print("Array Shape: ", arr2d.shape)
print("Dimensions: ", arr2d.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array Shape:  (3, 5)
Dimensions:  2


__Three Dimentional Array__

In [6]:
arr3 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(arr3)
print("\nArray Shape: ", arr3.shape)
print("Dimensions: ", arr3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]

Array Shape:  (3, 2, 5)
Dimensions:  3


__Reshaping the Arrays__

__Syntax:__ *numpy.reshape(a, newshape, order='C')*

In [7]:
array1 = np.arange(24)
print(array1)
print("Array Shape: ", array1.shape)
print("Number of Dimensions:", array1.ndim)

print('\n')
array2 = array1.reshape(3,2,4) 
print(array2)
print("Array Shape: ", array2.shape)
print("Number of Dimensions:", array2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Array Shape:  (24,)
Number of Dimensions: 1


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
Array Shape:  (3, 2, 4)
Number of Dimensions: 3


__Performing Operations in Arrays__

In [8]:
array2 = np.array([1, 2, 3, 4])
print(array2.dtype)
array2*2

int32


array([2, 4, 6, 8])

__Transposing an Array__

__Syntax:__ *numpy.transpose(a, axes=None)*

In [9]:
arra2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arra2)
np.transpose(arra2)

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

__Setting the Data Type of the Array__

In [10]:
array3 = np.array([1, 2, 3, 4], dtype='int64')
print(array3)
print(array3.dtype)

[1 2 3 4]
int64


__Converting the Array's Datatype__

__Syntax:__ *ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)*

In [11]:
array4 = np.array([1, 2, 3])
array4 = array4.astype('f')
print(array4)
print(array4.dtype)

[1. 2. 3.]
float32


In [12]:
array5 = np.array([1.2, 2.2, 3.9])
array5 = array5.astype('i')
print(array5)
print(array5.dtype)

[1 2 3]
int32


__Converting to array__

__Syntax:__ *numpy.asarray(a, dtype=None, order=None, *, like=None)*

In [13]:
a = [1, 2]
np.asarray(a)

array([1, 2])

__Creating an array x with refernce y and copying it to z__

__Syntax:__ *numpy.copy(a, order='K', subok=False)*

In [14]:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)

__Spliting an Array__

__Syntax:__ *numpy.split(ary, indices_or_sections, axis=0)*

In [15]:
arra3 = np.arange(21)
print(arra3)
np.split(arra3, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20])]

__Appending in an Array__

__Syntax:__ *numpy.append(arr, values, axis=None)*

In [16]:
arra4 = np.arange(3)
print(arra4)
arra4 = np.append(arra4, [[4, 5, 6], [7, 8, 9]])
print(arra4)

[0 1 2]
[0 1 2 4 5 6 7 8 9]


__Inserting in an Array__

__Syntax:__ *numpy.insert(arr, obj, values, axis=None)*

In [17]:
arra5 = np.array([[1, 1], [2, 2], [3, 3]])
print(arra5)
arra5 = np.insert(arra5, 1, 5, axis = 1)
print("\n",arra5)

[[1 1]
 [2 2]
 [3 3]]

 [[1 5 1]
 [2 5 2]
 [3 5 3]]


__Deleting elements in an array__

__Syntax:__ *numpy.delete(arr, obj, axis=None)*

In [18]:
arra6 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arra6)
np.delete(arra6, 1, 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [7, 8, 9]])

__Note:__ The array should be homogenous, that is all the elements in the array should be of the same datatype.

## Thank you!