# Day 21 of 100 Days of Data Science

---
## NumPy: Array Operations

An Array can have the following operations:
   - Bitwise
   - String
   - Mathematical
   - Statistical

In [1]:
import numpy as np

__Bitwise Operations__

In [22]:
num1 = 25
num2 = 18
print("Number 1:", num1, "Binary:", np.binary_repr(num1))
print("Number 2:", num2, "Binary:", np.binary_repr(num2)) 
Bitwise_OR_operator = np.bitwise_or(num1, num2)
Bitwise_AND_operator = np.bitwise_and(num1, num2)
print("Bitwise_OR_operator:", Bitwise_OR_operator, "Binary Representation:", np.binary_repr(Bitwise_OR_operator))
print("Bitwise_AND_operator:", Bitwise_AND_operator, "Binary Representation:", np.binary_repr(Bitwise_AND_operator))

Number 1: 25 Binary: 11001
Number 2: 18 Binary: 10010
Bitwise_OR_operator: 27 Binary Representation: 11011
Bitwise_AND_operator: 16 Binary Representation: 10000


In [25]:
num1 = 73
num2 = 85  
Bitwise_OR_operator = np.bitwise_or(num1, num2)
Bitwise_AND_operator = np.bitwise_and(num1, num2)
print("Bitwise_OR_operator:", Bitwise_OR_operator, "Binary Representation:", np.binary_repr(Bitwise_OR_operator))
print("Bitwise_AND_operator:", Bitwise_AND_operator, "Binary Representation:", np.binary_repr(Bitwise_AND_operator))

Bitwise_OR_operator: 93 Binary Representation: 1011101
Bitwise_AND_operator: 65 Binary Representation: 1000001


__String operations__

__Add__

In [4]:
str_array1 = np.array(['a1','b','c','d','e', 'a'])
str_array2 = np.array(['x','y','z','a','b', 'a'])
np.char.add(str_array1 , str_array2)

array(['a1x', 'by', 'cz', 'da', 'eb', 'aa'], dtype='<U3')

In [5]:
str_array1 = np.array(['a','b','c','d','e'])
str_array2 = 'a'
np.char.add(str_array1 , str_array2)

array(['aa', 'ba', 'ca', 'da', 'ea'], dtype='<U2')

__Multiply__

In [6]:
str_array1 = np.array(['ab','b','c','d','e'])
np.char.multiply(str_array1 , 4)

array(['abababab', 'bbbb', 'cccc', 'dddd', 'eeee'], dtype='<U8')

__Capitalize__

In [26]:
np.char.capitalize('sonic')

array('Sonic', dtype='<U5')

In [27]:
np.char.capitalize(np.char.multiply(str_array1 , 3))

array(['Ababab', 'Bbb', 'Ccc', 'Ddd', 'Eee'], dtype='<U6')

__Upper or Lower funtion__

In [11]:
print(np.char.upper(str_array1))
np.char.lower(str_array1)

['AB' 'B' 'C' 'D' 'E']


array(['ab', 'b', 'c', 'd', 'e'], dtype='<U2')

__Strip__

In [12]:
str_array3 = np.array(['  x   ',' y ',' z ',' a  ','  b   '])
print(str_array3)
print(np.char.strip(str_array3))

['  x   ' ' y ' ' z ' ' a  ' '  b   ']
['x' 'y' 'z' 'a' 'b']


__Replace__

In [13]:
np.char.replace (str_array3, 't', 'a')

array(['  x   ', ' y ', ' z ', ' a  ', '  b   '], dtype='<U6')

__Mathematical Operation__

In [14]:
m_array1 = np.array([1,2,3,4,5])
m_array2 = np.array([2,2,2,2,2])

print("Addition:", m_array1 + m_array2)
print("Multiplication:", m_array1 * m_array2)
print("Subtract:", m_array1 - m_array2)

Addition: [3 4 5 6 7]
Multiplication: [ 2  4  6  8 10]
Subtract: [-1  0  1  2  3]


__Power__

In [15]:
m_array1 = np.array([1,2,3,4,5])
m_array2 = np.array([2,2,2,2,2])
print(np.power(m_array1,m_array2))
print(np.power(m_array1,2))

[ 1  4  9 16 25]
[ 1  4  9 16 25]


__Statistical Operations__

In [16]:
m_array4 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) 
print("Min:", np.amin(m_array4))
print("Max:", np.amax(m_array4))

Min: 1
Max: 15


In [28]:
print(m_array4)
print("Min:", np.amin(m_array4, axis = 1)) 
print("Max:", np.amax(m_array4, axis = 0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Min: [ 1  6 11]
Max: [11 12 13 14 15]


In [18]:
print("Median:", np.median(m_array4, 1))

Median: [ 3.  8. 13.]


In [19]:
print("Average:", np.average(m_array4, 0))
print("Mean:", np.mean(m_array4, 0))
print("Variance:", np.var(m_array4, 0))

Average: [ 6.  7.  8.  9. 10.]
Mean: [ 6.  7.  8.  9. 10.]
Variance: [16.66666667 16.66666667 16.66666667 16.66666667 16.66666667]


In [20]:
print("Percentile:", np.percentile(m_array4, 100, axis = 0))

Percentile: [11. 12. 13. 14. 15.]


## Thank You!