# Day 22 of 100 Days of Data Science

---
## NumPy: Sort, Search and Filter

__Sort:__ Sorting means putting elements in an ordered sequence.

__Search:__ Searching is when we have to find an element from the given array.

__Filter:__ Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [1]:
import numpy as np

### Sorting

__Sorting 1-D Array__

In [2]:
array1 = np.array([56, 12, 34, 21, 89, 45, 32, 13])
print(array1)
print(np.sort(array1))

[56 12 34 21 89 45 32 13]
[12 13 21 32 34 45 56 89]


__Reversing the Sort Order__

In [3]:
print(np.sort(array1)[::-1])

[89 56 45 34 32 21 13 12]


__Sorting String Array__

In [4]:
str_array1 = np.array(['x','y','z','ab','b', 'aa'])
print(np.sort(str_array1))

['aa' 'ab' 'b' 'x' 'y' 'z']


__Sorting 2-D Array__

In [5]:
array2 = np.array([[46,3,23,78,98], [78,46,86,2,23], [78,56,34,65,23]]) 
print(array2)
print(np.sort(array2))

[[46  3 23 78 98]
 [78 46 86  2 23]
 [78 56 34 65 23]]
[[ 3 23 46 78 98]
 [ 2 23 46 78 86]
 [23 34 56 65 78]]


__Sorting 2-D Arrays with Axis__

In [6]:
print(np.sort(array2, axis = 0))

[[46  3 23  2 23]
 [78 46 34 65 23]
 [78 56 86 78 98]]


__Sorting Arrays by setting a kind__

In [7]:
print(np.sort(array2, axis = 0, kind = 'mergesort'))

[[46  3 23  2 23]
 [78 46 34 65 23]
 [78 56 86 78 98]]


In [8]:
print(array2)
print(np.msort(array2)) # Sort based on first axis

[[46  3 23 78 98]
 [78 46 86  2 23]
 [78 56 34 65 23]]
[[46  3 23  2 23]
 [78 46 34 65 23]
 [78 56 86 78 98]]


### Searching

In [9]:
array1 = np.array([56, 12, 34, 21, 89, 45, 32, 13])
np.where(array1 == 34)

(array([2], dtype=int64),)

__Searching with conditions__

In [10]:
np.where(array1%2 == 0)

(array([0, 1, 2, 6], dtype=int64),)

__Extracting where conditions are met__ 

In [11]:
np.extract(array1%2 == 0, array1)

array([56, 12, 34, 32])

__Where to insert to retain sort order__

In [18]:
print(np.searchsorted(array1, 33))
np.searchsorted(array1, 336)

2


8

In [13]:
np.searchsorted(array1, [33, 4, 76])

array([2, 0, 4], dtype=int64)

__Finding the position with min and max values__

In [14]:
np.argmin(array1)

1

In [15]:
array2 = np.array([[12,2,33,44,15],[61,17,28,39,1],[16,22,3,41,15]]) 
print(array2)
print("Position of minimum value", np.argmin(array2))
print("Position of minimum values by rows", np.argmin(array2, axis = 1))
print("Position of minimum values by column", np.argmin(array2, axis = 0))

[[12  2 33 44 15]
 [61 17 28 39  1]
 [16 22  3 41 15]]
Position of minimum value 9
Position of minimum values by rows [1 4 2]
Position of minimum values by column [0 0 2 1 1]


In [16]:
array2 = np.array([[12,2,33,44,15],[61,17,28,39,1],[16,22,3,41,15]]) 
print(array2)
print("Position of maximum values", np.argmax(array2))

[[12  2 33 44 15]
 [61 17 28 39  1]
 [16 22  3 41 15]]
Position of maximum values 5


### Filtering

In [17]:
array2 = np.array([[12,2,33,44,15],[61,17,28,39,1],[16,22,3,41,15]]) 
condition = array2 > 19

filtered_array = array2[array2 < 19]
print(filtered_array)

[12  2 15 17  1 16  3 15]


## Thank You!