# Day 19 of 100 Days of Data Science

---
## NumPy: Indexing, Slicing, Join and Split

__Indexing:__ A way to refer the individual items within an iterable by its position. 

__Slicing:__ Taking elements from one given index to another given index.

__Joining:__ Joining 2 or more arrays into one

__Spliting:__ Dividing an array into 2 or more arrays

In [1]:
import numpy as np

__Creating an array of the following types__

__One Dimentional Array__

In [2]:
arr1 = np.arange(20)
print(arr1)
print("Array Shape: ", arr1.shape)
print("Number of Dimensions:", arr1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array Shape:  (20,)
Number of Dimensions: 1


__Two Dimentional Array__

In [3]:
arr2 = arr1.reshape(2,10) 
print(arr2)
print("Array Shape: ", arr2.shape)
print("Number of Dimensions:", arr2.ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Array Shape:  (2, 10)
Number of Dimensions: 2


__Three Dimentional Array__

In [4]:
arr3 = arr1.reshape(2,2,5) 
print(arr3)
print("Array Shape: ", arr3.shape)
print("Number of Dimensions:", arr3.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
Array Shape:  (2, 2, 5)
Number of Dimensions: 3


__Indexing in One Dimentional Array__

In [5]:
print(arr1)
print("Element in 3rd Position", arr1[2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Element in 3rd Position 2


__Indexing in Two Dimentional Array__

In [6]:
print(arr2)
print('5th element on 2nd dim: ', arr2[1, 4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
5th element on 2nd dim:  14


__Indexing in Three Dimentional Array__

In [7]:
print(arr3)
print('5th element on 2nd dim in the first array: ', arr3[0, 1, 4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
5th element on 2nd dim in the first array:  9


__Negative Idexing__

In [31]:
print(arr2)
print(' Second Last element: ', arr2[1, -2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
 Second Last element:  18


__Slicing in One Dimentional Array__

In [9]:
print(arr1)
print(arr1[:7])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6]


__Slicing in Two Dimentional Array__

In [25]:
print(arr2)
print("\n",arr2[0, 1:4])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

 [1 2 3]


__Slicing in Three Dimentional Array__

In [24]:
print(arr3)
print("\n\n",arr3[:, 1:4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


 [[[ 5  6  7  8  9]]

 [[15 16 17 18 19]]]


__Joining One Dimentional Array__

In [12]:
d1 = np.array([1, 2, 3, 4, 5])
d2 = np.array([6, 7, 8, 9, 10])
new_data1 = np.concatenate((d1, d2))
print(new_data1)

[ 1  2  3  4  5  6  7  8  9 10]


__Joining Two Dimentional Array__

In [13]:
dat1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
dat2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_dat1 = np.concatenate((dat1, dat2))
print(new_dat1)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]


__Joining by Column__

In [14]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data2 = np.concatenate((data1, data2), axis = 1)
print(new_data2)
print(new_data2.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
(2, 10)


__Stacking Arrays__

In [15]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data3 = np.stack((data1, data2))
print(new_data3)
print(new_data3.shape)

[[[ 1  2  3  4  5]
  [ 1  2  3  4  5]]

 [[ 6  7  8  9 10]
  [ 6  7  8  9 10]]]
(2, 2, 5)


__Stacking Arrays Horizontally__

In [16]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data4 = np.hstack((data1, data2))
print(new_data4)
print(new_data4.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
(2, 10)


__Stacking Arrays Vertically__

In [17]:
data1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
data2 = np.array([[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]])
new_data5 = np.vstack((data1, data2))
print(new_data5)
print(new_data5.shape)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
(4, 5)


__Spliting Array__

In [18]:
data = np.array([1, 2, 3, 4, 5, 6])
new_array1 = np.array_split(data, 3)
print(new_array1)
print(new_array1[0])
print(new_array1[1])
print(new_array1[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


__Spliting Two Dimentional Array__

In [19]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_array2 = np.array_split(data, 3)
print(data)
print(new_array2)
print(new_array2[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[1 2 3]
 [4 5 6]]


__Spliting by Columns in a Two Dimentional Array__

In [20]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_array3 = np.array_split(data, 3, axis = 1)
print(data)
print(new_array3)
print(new_array3[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


## Thank you!