# Day 20 of 100 Days of Data Science

---
## NumPy: Iteration, Manipulation, and Random Numbers

__Iteration:__ Iterating means going through elements one by one.

__Manipulation:__ Can be done by many ways, changing shape, transposing, joining, etc.

__Random Numbers:__ Refers to generating random values in an array.

### Iteration 

In [1]:
import numpy as np

__Iterating One Dimensional Array__

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
i = 0
for x in arr1:
    print(x)
    i = i+1
    print(i)

1
1
2
2
3
3
4
4
5
5


__Creating a Random 1-D Array and printing only the Even Numbers__

In [42]:
arr = np.random.randint(1,101, 100)
print(arr, "\n")
i = 0
for x in arr:
    if(arr[x]%2==0):
        print(arr[x])
    i= i+1

[26 60  1 59 89 61 13 46 62 60 62 55 48 10  4 67 15 50 99 86 17 58 92 61
 35 25 20 44 76 82 15 91 88 81 49 36 80 71 57 71 91 35 68 27 81 11 33 34
  1 31  1 28 34 37 89 55 29 50 24 86 46 75 57 78 44 78 95 89 86 81 69 90
 69 93 27 56 82  5 99 33  1 78 95 65 37  2 16 70 67 50 94 63 19 48  4 25
 12 44 68 82] 

20
46
60
86
50
10
46
62
82
16
50
24
36
82
78
80
90
50
90
36
86
44
78
60
60
76
50
82
16
56
50
50
16
78
94
48
44
82
60
78
4
78
86
48
86


__Iterating Two Dimensional Array__

In [17]:
arr2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[6, 7, 8, 9, 10]])
print(arr2, "\n")
i = 0
for x in arr2:
    print(x)
    i = i + 1
    print (i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]] 

[1 2 3 4 5]
1
[ 6  7  8  9 10]
2
[ 6  7  8  9 10]
3


__Iterating elements in Two Dimensional Array__

In [4]:
arr3 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
for i in arr3:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


__Iterating Three Dimensional Array__

In [20]:
arr4 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])
print(arr4, "\n\n")
i = 0
for x in arr4:
    print(x)
    i = i + 1
    

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] 


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


__Iterating The elements of a Three Dimensional Array__

In [6]:
arr5 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])

for i in arr5:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


__Using nditer to Loop__

__Syntax:__ *class numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)*

In [7]:
arr6 = np.array([[[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]])
z = 0
for i in np.nditer(arr6):
    print(i)
    z = z +1
    print(z)

1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
1
11
2
12
3
13
4
14
5
15
6
16
7
17
8
18
9
19
10
20


### Manipulation

__Reshaping 1-D to a higher Dimension__

__Syntax:__ *numpy.reshape(a, newshape, order='C')*

In [8]:
array1 = np.arange(30)
print(array1)
array2 = array1.reshape(3,10) 
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


__Reshaping Higher Dimension to 1-D__

In [9]:
array3 = array2.flatten()
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


__Transpose__

In [10]:
print(array2)
print(array2.T)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]


__Roll Axis__

__Syntax:__ *numpy.rollaxis(a, axis, start=0)*

In [11]:
print(np.rollaxis(array2,1))

[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]


### Random Numbers

In [12]:
from numpy import random

__Generating Random Numbers__

In [13]:
random.rand()

0.07181715083841678

__Generating Random 1-D Array__

In [14]:
r_array1 = random.randint(25, size=(5))
print(r_array1)

[ 2 20  1 21 22]


__Generating Random 2-D Array__

In [15]:
r_array2 = random.randint(250, size=(5, 5))
print(r_array2)

[[ 20  15  69 213  80]
 [ 66 219 101 190 100]
 [ 49 242 192  17 147]
 [166 211  28 156 242]
 [208  79  41  72 186]]


__Generating Arrays with Certain Numbers only__

In [16]:
r_array3 = random.choice([1, 2, 3, 4, 5], p=[0.1, 0.2, 0.4, 0.2, 0.1], size=(100))
print(r_array3)

[2 2 3 5 4 3 2 3 2 3 3 3 2 2 4 3 2 3 4 2 3 3 3 3 2 3 1 2 4 2 1 1 4 3 3 4 1
 5 5 3 3 1 3 3 4 3 3 3 3 5 4 3 2 1 3 2 3 3 3 3 3 5 3 2 2 5 3 3 4 4 3 2 3 1
 3 3 2 1 4 1 3 5 2 3 3 4 4 3 1 3 3 5 4 5 3 2 5 4 4 3]


__Creating a random 1-D Array and converting it into 3-D Array__

In [51]:
r_arr1 = random.randint(50, size=(20))
print(r_arr1)

r_arr1 = r_arr1.reshape(2, 2, 5)
r_arr1

[ 8 29 34 47 43 33 31 43 41 25 36  1 17 14  3 43  0 30  7 44]


array([[[ 8, 29, 34, 47, 43],
        [33, 31, 43, 41, 25]],

       [[36,  1, 17, 14,  3],
        [43,  0, 30,  7, 44]]])

## Thank You!